### PR TITLE
[Feature] Add Slack to Footer

### LINKED ISSUE #60: [Feature] Add Slack to Website Footer
### Description

Add organization's Slack Workspace link to website footer :)

### Designs

_No response_

### PR DESCRIPTION
**Pull request by jefferyjohn**
# Description

Transition from Mattermost to Slack by uploading new icon and adding go.scottylabs link

## Type of change

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by jefferyjohn** [comment]
## Desktop
image

## Tablet
image

## Mobile
image

**Comment by hdavidethan** [comment]
I think the icons are not up to date in the downstream repo. We revised how we handle the icons to ensure the best performance for loading the images.

Please use this svg for the Slack logo: https://brandfolder.com/slack/logos#!asset/pl546j-7le8zk-450dp9

Code pointer here:
https://github.com/ScottyLabs/scottylabs.org/blob/main/src/icons/MattermostIcon/index.tsx

**Review by hdavidethan — CHANGES_REQUESTED** [review]
See previous comment

**Comment by jefferyjohn** [comment]
in tears resizing the icon

**Comment by gramliu** [comment]
@jefferyjohn I think I found a way to get it to fit, although I used the svg icon that @hdavidethan linked

image

**Comment by gramliu** [comment]
Merged in #60

**Pull request closed without merging**
